import type { MenuItem } from "./types";

export const menu: MenuItem[] = [
  {
    id: "spicy_chicken_sandwich",
    name: "Spicy Chicken Sandwich",
    description: "Buttermilk-fried chicken thigh with pickled jalapeños and chili aioli on a toasted brioche bun.",
    price: 14.5,
    category: "main",
    modifiers: ["extra spicy", "no pickles", "gluten-free bun"],
  },
  {
    id: "grilled_atlantic_salmon",
    name: "Grilled Atlantic Salmon",
    description: "Cedar-plank salmon glazed with lemon-dill butter, served over wild rice pilaf.",
    price: 22.0,
    category: "main",
    modifiers: ["medium", "well done"],
  },
  {
    id: "wild_mushroom_risotto",
    name: "Wild Mushroom Risotto",
    description: "Creamy arborio rice with cremini, shiitake, and oyster mushrooms finished with parmesan.",
    price: 18.0,
    category: "main",
    modifiers: ["vegan", "extra parmesan"],
  },
  {
    id: "bistro_classic_burger",
    name: "Bistro Classic Burger",
    description: "Half-pound grass-fed beef patty with aged cheddar, caramelized onions, and house sauce.",
    price: 16.0,
    category: "main",
    modifiers: ["medium rare", "medium", "well done", "no onions", "add bacon"],
  },
  {
    id: "truffle_parmesan_fries",
    name: "Truffle Parmesan Fries",
    description: "Hand-cut russet fries tossed in truffle oil, shaved parmesan, and fresh parsley.",
    price: 8.5,
    category: "side",
  },
  {
    id: "little_gem_caesar",
    name: "Little Gem Caesar",
    description: "Crisp little gem lettuce with anchovy dressing, garlic croutons, and pecorino.",
    price: 9.0,
    category: "side",
    modifiers: ["no anchovy", "add chicken"],
  },
  {
    id: "still_water",
    name: "Still Water",
    description: "Filtered still water served chilled.",
    price: 4.0,
    category: "drink",
    modifiers: ["small", "large"],
  },
  {
    id: "house_iced_tea",
    name: "House Iced Tea",
    description: "Cold-brewed black tea with a hint of lemon and mint.",
    price: 5.0,
    category: "drink",
    modifiers: ["unsweetened", "lightly sweetened", "extra lemon"],
  },
  {
    id: "chocolate_lava_cake",
    name: "Chocolate Lava Cake",
    description: "Warm dark chocolate cake with a molten center, served with vanilla bean ice cream.",
    price: 10.0,
    category: "dessert",
  },
  {
    id: "seasonal_fruit_tart",
    name: "Seasonal Fruit Tart",
    description: "Buttery shortcrust filled with vanilla pastry cream and topped with fresh seasonal fruit.",
    price: 9.5,
    category: "dessert",
  },
];
